// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package local handles command line parameters and execution logic for local run
package local

import (
	"fmt"
	"net/url"
	"os/exec"
	"path"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/spf13/cobra"
	"google.golang.org/adk/cmd/adkgo/root/run"
	"google.golang.org/adk/internal/cli/util"
)

type localServerFlags struct {
	port int // command line param
}

type buildFlags struct {
	execPath string // command line param, autogenerated if absent
}

type sourceFlags struct {
	srcBasePath    string // autogenerated
	entryPointPath string // command line param
}

type webUIDeployFlags struct {
	backendUri string // autogenerated
}

type runLocalFlags struct {
	server localServerFlags
	build  buildFlags
	source sourceFlags
	webUI  webUIDeployFlags
}

var flags runLocalFlags

// localCmd represents the cloudrun command
var localCmd = &cobra.Command{
	Use:   "local",
	Short: "Runs a local server with WebUI and API.",
	Long: `
	Starts a local server on the given port. ADK Web UI runs on '/ui/' and ADK REST API runs on '/api/'
	You need static content of ADK Web UI (comes with adk-go sources).
	`,
	RunE: func(cmd *cobra.Command, args []string) error {
		err := flags.runLocal()
		return err
	},
}

func init() {
	run.RunCmd.AddCommand(localCmd)

	localCmd.PersistentFlags().IntVarP(&flags.server.port, "server_port", "p", 8080, "Localhost port on which the server should be listening")
	localCmd.PersistentFlags().StringVarP(&flags.source.entryPointPath, "entry_point_path", "e", "", "Path to an entry point (go 'main'). Example relative to ADK-GO repo: './examples/web/main.go'")
	localCmd.PersistentFlags().StringVarP(&flags.build.execPath, "target_exec_path", "t", "", "Path to the output executable. Defaults to entry_point_path with no '.go' suffix.")
}

func (f *runLocalFlags) computeFlags() error {
	return util.LogStartStop("Computing flags",
		func(p util.Printer) error {
			// make paths absolute
			absp, err := filepath.Abs(flags.source.entryPointPath)
			if err != nil {
				return fmt.Errorf("cannot make an absolute path from '%v': %w", flags.source.entryPointPath, err)
			}
			flags.source.entryPointPath = absp

			dir, file := path.Split(f.source.entryPointPath)
			f.source.srcBasePath = dir
			f.source.entryPointPath = file
			if f.build.execPath == "" {
				exec, err := util.StripExtension(f.source.entryPointPath, ".go")
				if err != nil {
					return err
				}
				absp, err = filepath.Abs(exec)
				if err != nil {
					return fmt.Errorf("cannot make an absolute path from '%v': %w", exec, err)
				}
				f.build.execPath = absp
			}
			u := "http://localhost:" + strconv.Itoa(f.server.port)
			url, err := url.JoinPath(u, "api")
			if err != nil {
				return fmt.Errorf("JoinPath failed for '%v': %w", u, err)
			}
			f.webUI.backendUri = url

			p(fmt.Sprintf("%+v", f))
			return nil
		})
}

func (f *runLocalFlags) compileEntryPoint() error {
	return util.LogStartStop("Compiling server",
		func(p util.Printer) error {
			p("Using", f.source.entryPointPath, "as entry point")
			cmd := exec.Command("go", "build", "-o", f.build.execPath, f.source.entryPointPath)

			cmd.Dir = f.source.srcBasePath
			return util.LogCommand(cmd, p)
		})
}

func (f *runLocalFlags) runLocalServer() error {
	return util.LogStartStop("Running local server",
		func(p util.Printer) error {
			cmd := exec.Command(f.build.execPath,
				"--port", strconv.Itoa(f.server.port),
				"--webui_address", "localhost:"+strconv.Itoa(f.server.port),
				"--api_server_address", "http://localhost:"+strconv.Itoa(f.server.port)+"/api",
			)

			cmd.Dir = f.source.srcBasePath
			targetWidth := 80

			p(strings.Repeat("-", targetWidth))
			p(util.CenterString("", targetWidth))
			p(util.CenterString("Running ADK Web UI on http://localhost:"+strconv.Itoa(f.server.port)+"/ui/    <-- open this", targetWidth))
			p(util.CenterString("ADK REST API on http://localhost:"+strconv.Itoa(f.server.port)+"/api/         ", targetWidth))
			p(util.CenterString("", targetWidth))
			p(util.CenterString("Press Ctrl-C to stop", targetWidth))
			p(util.CenterString("", targetWidth))
			p(strings.Repeat("-", targetWidth))
			return util.LogCommand(cmd, p)
		})
}

func (f *runLocalFlags) runLocal() error {
	err := f.computeFlags()
	if err != nil {
		return err
	}
	err = f.compileEntryPoint()
	if err != nil {
		return err
	}
	err = f.runLocalServer()
	if err != nil {
		return err
	}

	return nil
}
